# Generated by Django 5.2.8 on 2025-11-11 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KycDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_proof_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="kyc/id_proofs/"
                    ),
                ),
                (
                    "selfie_image",
                    models.ImageField(blank=True, null=True, upload_to="kyc/selfies/"),
                ),
                (
                    "document_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("verified", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
